name: Python MIDI Decrypt and Song Processing

on:
  push:
    branches:
      - main

jobs:
  decrypt-and-process:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
          # Install dependencies (requests, mido, etc.)
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests mido pycryptodome 

      # Run the Python script
    - name: Run the script
      run: python scripts/all.py  # Replace with the actual path to your Python script

  
    - name: Run Song Processing Script
      run: |
        chmod +x process_songs.sh
        ./process_songs.sh

    - name: Save output files
      run: |
        mkdir -p output
        mv final_output.txt output/
        mv paths output/

    - name: Commit and push artifact
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git pull origin main
        git add final_output.txt paths
        git commit -m "Add final_output.txt and paths folder"
        git push origin main
      env:
      GH_PAT: ${{ secrets.GH_PAT }}