name: Python MIDI Decrypt and Song Processing

on:
  push:
    branches:
      - main

jobs:
  decrypt-and-process:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
          # Install dependencies (requests, mido, etc.)
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests mido pycryptodome 

      # Run the Python script
    - name: Run the script
      run: python scripts/all.py  # Replace with the actual path to your Python script

  
    - name: Run Song Processing Script
      run: |
        chmod +x process_songs.sh
        ./process_songs.sh